version: '3.3'

services:
  devmail:
    env_file:
      - .docker/.env
    image: djfarrelly/maildev
    ports:
      - ${HTTP_DEVMAIL_PORT}:80
  mariadb:
    user: 501:1000
    volumes:
      - mariadbData:/var/lib/mysql
  nginx:
    env_file:
      - .docker/.env
    volumes:
      - ./public:/var/www/public
  php-fpm:
    env_file:
      - .docker/.env
    build:
      target: development
    working_dir: /var/www
    volumes:
      - applicationData:/var/www
      - ./.docker/.composerAuth.json:/root/.config/composer/auth.json
      - ./.docker/composer:/.composer

volumes:
  mariadbData:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data$PWD/.docker/database"
  applicationData:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data$PWD"
