version: '3.3'

services:
  devmail:
    env_file:
      - .docker/.env
    image: djfarrelly/maildev
    ports:
      - ${HTTP_DEVMAIL_PORT}:80
  mysql:
    volumes:
      - ./.docker/database:/var/lib/mysql
  nginx:
    env_file:
      - .docker/.env
    volumes:
      - ./public:/var/www/public
  php-fpm:
    environment:
      NETTE_ENV: dev
      NETTE_DEBUG: 1
      COMPOSER_MEMORY_LIMIT: -1
    links:
      - devmail
    build:
      target: development
    working_dir: /var/www
    volumes:
      - applicationData:/var/www
      - ./.docker/.composerAuth.json:/root/.config/composer/auth.json
      - ./.docker/composer:/.composer

volumes:
  applicationData:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data$PWD"
