ALTER TABLE sf_order ADD customer_id INT DEFAULT NULL;
ALTER TABLE sf_order ADD CONSTRAINT FK_6148EE629395C3F3 FOREIGN KEY (customer_id) REFERENCES sf_customer (id) ON DELETE SET NULL;
CREATE INDEX IDX_6148EE629395C3F3 ON sf_order (customer_id);
