ALTER TABLE sf_credit_note ADD company_id VARCHAR(255) DEFAULT NULL, ADD vat_id VARCHAR(255) DEFAULT NULL, ADD tax_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE sf_proforma_invoice ADD company_id VARCHAR(255) DEFAULT NULL, ADD vat_id VARCHAR(255) DEFAULT NULL, ADD tax_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE sf_invoice ADD company_id VARCHAR(255) DEFAULT NULL, ADD vat_id VARCHAR(255) DEFAULT NULL, ADD tax_id VARCHAR(255) DEFAULT NULL;
