CREATE TABLE sf_users_projects (project_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_B869463F166D1F9C (project_id), INDEX IDX_B869463FA76ED395 (user_id), PRIMARY KEY(project_id, user_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;
ALTER TABLE sf_users_projects ADD CONSTRAINT FK_B869463F166D1F9C FOREIGN KEY (project_id) REFERENCES sf_projects (id) ON DELETE CASCADE;
ALTER TABLE sf_users_projects ADD CONSTRAINT FK_B869463FA76ED395 FOREIGN KEY (user_id) REFERENCES core_user (id) ON DELETE CASCADE;
