ALTER TABLE sf_invoice ADD customer_id INT DEFAULT NULL, ADD email VARCHAR(255) DEFAULT NULL, ADD phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE sf_invoice ADD CONSTRAINT FK_508287939395C3F3 FOREIGN KEY (customer_id) REFERENCES sf_customer (id) ON DELETE SET NULL;
CREATE INDEX IDX_508287939395C3F3 ON sf_invoice (customer_id);
ALTER TABLE sf_credit_note ADD customer_id INT DEFAULT NULL, ADD email VARCHAR(255) DEFAULT NULL, ADD phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE sf_credit_note ADD CONSTRAINT FK_4B4DB629395C3F3 FOREIGN KEY (customer_id) REFERENCES sf_customer (id) ON DELETE SET NULL;
CREATE INDEX IDX_4B4DB629395C3F3 ON sf_credit_note (customer_id);
ALTER TABLE sf_proforma_invoice ADD customer_id INT DEFAULT NULL, ADD email VARCHAR(255) DEFAULT NULL, ADD phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE sf_proforma_invoice ADD CONSTRAINT FK_73D7983D9395C3F3 FOREIGN KEY (customer_id) REFERENCES sf_customer (id) ON DELETE SET NULL;
CREATE INDEX IDX_73D7983D9395C3F3 ON sf_proforma_invoice (customer_id);
