UPDATE sf_invoice SET vat = null WHERE vat ='';
UPDATE sf_invoice SET vat_rate = null WHERE vat_rate ='';
UPDATE sf_invoice SET to_pay = null WHERE to_pay ='';
UPDATE sf_invoice SET with_vat = null WHERE with_vat ='';
UPDATE sf_invoice SET without_vat = null WHERE without_vat ='';
UPDATE sf_invoice SET exchange_rate = null WHERE exchange_rate ='';
UPDATE sf_invoice SET weight = null WHERE weight ='';
UPDATE sf_invoice SET complete_package_weight = null WHERE complete_package_weight ='';
update sf_invoice_item set vat_rate = '0' WHERE vat_rate = '0.00';

ALTER TABLE sf_credit_note CHANGE vat vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat_rate vat_rate INT DEFAULT NULL, CHANGE to_pay to_pay DOUBLE PRECISION DEFAULT NULL, CHANGE with_vat with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE without_vat without_vat DOUBLE PRECISION DEFAULT NULL, CHANGE exchange_rate exchange_rate DOUBLE PRECISION DEFAULT NULL, CHANGE weight weight DOUBLE PRECISION DEFAULT NULL, CHANGE complete_package_weight complete_package_weight DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE sf_proforma_invoice CHANGE vat vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat_rate vat_rate INT DEFAULT NULL, CHANGE to_pay to_pay DOUBLE PRECISION DEFAULT NULL, CHANGE with_vat with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE without_vat without_vat DOUBLE PRECISION DEFAULT NULL, CHANGE exchange_rate exchange_rate DOUBLE PRECISION DEFAULT NULL, CHANGE weight weight DOUBLE PRECISION DEFAULT NULL, CHANGE complete_package_weight complete_package_weight DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE sf_invoice CHANGE vat vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat_rate vat_rate INT DEFAULT NULL, CHANGE to_pay to_pay DOUBLE PRECISION DEFAULT NULL, CHANGE with_vat with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE without_vat without_vat DOUBLE PRECISION DEFAULT NULL, CHANGE exchange_rate exchange_rate DOUBLE PRECISION DEFAULT NULL, CHANGE weight weight DOUBLE PRECISION DEFAULT NULL, CHANGE complete_package_weight complete_package_weight DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE sf_order_item CHANGE price_ratio price_ratio DOUBLE PRECISION DEFAULT NULL, CHANGE item_price_vat_rate item_price_vat_rate INT DEFAULT NULL;
ALTER TABLE sf_invoice_item CHANGE amount amount DOUBLE PRECISION DEFAULT NULL, CHANGE weight weight DOUBLE PRECISION DEFAULT NULL, CHANGE price_ratio price_ratio DOUBLE PRECISION DEFAULT NULL, CHANGE with_vat with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE without_vat without_vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat_rate vat_rate INT DEFAULT NULL, CHANGE unit_with_vat unit_with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE unit_without_vat unit_without_vat DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE sf_credit_note_item CHANGE amount amount DOUBLE PRECISION DEFAULT NULL, CHANGE weight weight DOUBLE PRECISION DEFAULT NULL, CHANGE price_ratio price_ratio DOUBLE PRECISION DEFAULT NULL, CHANGE with_vat with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE without_vat without_vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat_rate vat_rate INT DEFAULT NULL, CHANGE unit_with_vat unit_with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE unit_without_vat unit_without_vat DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE sf_proforma_invoice_item CHANGE amount amount DOUBLE PRECISION DEFAULT NULL, CHANGE weight weight DOUBLE PRECISION DEFAULT NULL, CHANGE price_ratio price_ratio DOUBLE PRECISION DEFAULT NULL, CHANGE with_vat with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE without_vat without_vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat vat DOUBLE PRECISION DEFAULT NULL, CHANGE vat_rate vat_rate INT DEFAULT NULL, CHANGE unit_with_vat unit_with_vat DOUBLE PRECISION DEFAULT NULL, CHANGE unit_without_vat unit_without_vat DOUBLE PRECISION DEFAULT NULL;
