ALTER TABLE sf_credit_note ADD order_id INT DEFAULT NULL;
ALTER TABLE sf_credit_note ADD CONSTRAINT FK_4B4DB628D9F6D38 FOREIGN KEY (order_id) REFERENCES sf_order (id) ON DELETE SET NULL;
CREATE INDEX IDX_4B4DB628D9F6D38 ON sf_credit_note (order_id);
ALTER TABLE sf_proforma_invoice ADD order_id INT DEFAULT NULL;
ALTER TABLE sf_proforma_invoice ADD CONSTRAINT FK_73D7983D8D9F6D38 FOREIGN KEY (order_id) REFERENCES sf_order (id) ON DELETE SET NULL;
CREATE INDEX IDX_73D7983D8D9F6D38 ON sf_proforma_invoice (order_id);
ALTER TABLE sf_invoice ADD order_id INT DEFAULT NULL;
ALTER TABLE sf_invoice ADD CONSTRAINT FK_508287938D9F6D38 FOREIGN KEY (order_id) REFERENCES sf_order (id) ON DELETE SET NULL;
CREATE INDEX IDX_508287938D9F6D38 ON sf_invoice (order_id);
